### ISSUE TITLE
Combining focus and hover classes

### ISSUE THREAD

**Issue by lachlanjc** [tachyons-css/tachyons-skins#2]
Hey guys! Reading through the code in this module, I notice we've got 6 distinct kinds of utilities here:
1. text color
2. background color
3. focus text color
4. focus background color
5. hover text color
6. hover background color

I was just wondering, do we really need both focus _and_ hover classes? Are there really enough cases to justify the 1.5x increase in size? (Personally, I've never styled them separately, but I'm no accessibility expert.) I feel like combining them with one "active" class that styled on both hover and focus would make sense. If so, just let me know and I can PR.

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
