### ISSUE TITLE
Borders can't have a "moon-light" color

### ISSUE THREAD

**Issue by GRardB** [tachyons-css/tachyons-skins#8]
I noticed there's no `b--moon-light` class. I haven't dug deep to see if there are others like this, but is this intentional? If not, I can take a crack at opening a PR!

**Comment by mrmrs** [comment]
@GRardB Hey, Don't know if I follow - this is the skins module which is separate from the border-colors module. There is also no gray color called moon-light, just moon-gray. If you can clarify a bit what you're after - I'll try to help out.

**Comment by GRardB** [comment]
Wow, 0/2 for me! `moon-gray` is what I meant to type, yeah. Should I open an issue in the border-colors repo?

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
