### ISSUE TITLE
Empty css/tachyons-skins.css in 4.1.0

### ISSUE THREAD

**Issue by wKovacs64** [tachyons-css/tachyons-skins#9]
The contents of [`css/tachyons-skins.css`](../blob/d08ffebf2e33fe0fd2a757084732ecd951d483df/css/tachyons-skins.css) were wiped out in tachyons-skins 4.1.0. The [source](../blob/d08ffebf2e33fe0fd2a757084732ecd951d483df/src/tachyons-skins.css) is fine.

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
